pipeline:
  name: HelloWorld
  identifier: HelloWorld
  projectIdentifier: default_project
  orgIdentifier: default
  description: HelloWorldDotNet build and deploy pipeline using org pipeline template.
  tags: {}
  template:
    templateRef: org.BuildAndDeployDotNetApps
    versionLabel: v1
    templateInputs:
      properties:
        ci:
          codebase:
            build:
              spec:
                branch: main
              type: branch
      stages:
        - stage:
            identifier: Build
            type: CI
            spec:
              infrastructure:
                type: KubernetesDirect
                spec:
                  connectorRef: AKSSandpitConnector
                  namespace: default
              execution:
                steps:
                  - step:
                      identifier: Testing
                      type: Test
                      spec:
                        connectorRef: DockerHub
        - stage:
            identifier: Deploy_Hello_world
            type: Deployment
            spec:
              service:
                serviceRef: HelloWorldAKSSandpit
              environment:
                environmentRef: AKSSandpit2
                infrastructureDefinitions:
                  - identifier: AKSSandpit2
              execution:
                steps:
                  - stepGroup:
                      identifier: Canary_Deployment
                      steps:
                        - step:
                            identifier: K8sCanaryDeploy
                            type: K8sCanaryDeploy
                            spec:
                              instanceSelection:
                                type: Count
                                spec:
                                  count: 3
            delegateSelectors:
              - helm-delegate-sandpit
